# values-operator.yaml
replicaCount: 1

operatorImageRepository: docker.io/percona/percona-postgresql-operator
imagePullPolicy: IfNotPresent

# נעקוב רק אחרי הניימספייס שלנו
watchNamespace: "percona-postgres"

# לא לעקוב אחרי כל הקלאסטר
watchAllNamespaces: false

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

disableTelemetry: true
logLevel: "INFO"